backend:
  analytics: # Contents will be available in UI
    google_analytics_id: 
    matomo_analytics_id: 

elasticsearch:
  hosts:
    - "elasticsearch:9200"
  index_prefix: "turku_v2"
  index_reader_rolename: "turku_v2_index_reader"
  index_writer_rolename: "turku_v2_index_writer"
  languages: # Contents will be available in UI
    - fi
    - sv
    - en
  analyzers:
    default:
      tokenizer:
        "standard"
      token_filters:
        - "lowercase"
    fi:
      stop_stemmer:
        tokenizer:
          "standard"
        token_filters:
          - "lowercase"
          - type: "stop"
            stopwords: "_finnish_"
          - type: "stemmer_override"
            rules_path: "nlp_dictionary_fi.txt"
          - type: "stemmer"
            language: "finnish"
          - type: "synonym"
            synonyms_path: "synonyms_fi.txt"
    sv:
      stop_stemmer:
        tokenizer:
          "standard"
        token_filters:
          - "lowercase"
          - type: "stop"
            stopwords: "_swedish_"
          - type: "stemmer"
            language: "swedish"
          - type: "synonym"
            synonyms_path: "synonyms_sv.txt"
    en:
      stop_stemmer:
        tokenizer:
          "standard"
        token_filters:
          - "lowercase"
          - type: "stop"
            stopwords: "_english_"
          - type: "stemmer"
            language: "english"
          - type: "synonym"
            synonyms_path: "synonyms_en.txt"

  search_settings:
    fuzziness: 0
    field_boosts:
    # Boosts the score of the documents matching to the given field and value by multiplying the original score by the boost value.
    #   some_descriptive_name:
    #     field: "field_name" [str]
    #     values: "the_value_to_be_boosted" [str|list(str)]
    #     boost: 42.0 [integer|float]

  suggest_settings: # General settings for the suggest query made from the search backend. 
    suggest1: # Multiple suggestion can be configured if needed - copy this block, rename it and settings
      completion:
        field: "suggest" # Field to search for suggestion in
        skip_duplicates: true
        fuzzy:
          fuzziness: 0
        size: 20 # Amount of suggestions to return

SCRAPY_SETTINGS:
  GENERAL:
    DEPTH_LIMIT: 0
    DOWNLOAD_DELAY: 0.1
    DOWNLOAD_TIMEOUT: 180
    LOG_ENABLED: true
    LOG_FILE: filename.log # If set as null, log is sent into console
    LOG_FORMAT: '%(asctime)s [%(name)s] %(levelname)s: %(message)s'
    LOG_LEVEL: 'INFO'
    LOGSTATS_INTERVAL: 60
    ROBOTSTXT_OBEY: true

  SPIDERS:
    TurkuGenericSpider:
      BOT_NAME: "turku_v2_keha"
      ALLOWED_DOMAINS:
        - main.turku-v2.dev.wdr.io
      START_URLS:
        - "https://main.turku-v2.dev.wdr.io/sitemap.xml"
      LINK_EXTRACTOR_RULES:
        allow:
        deny:
          - "/search/"
          - "/en/search/"
          - "/sv/search/"

      # Custom settings are available through spider object.
      CUSTOM_SETTINGS:
        CRAWL_LINKS_ONLY:
          # The pages which have an url containing one of these paths are crawled and links are extracted without indexing the contents.
          # Suitable especially for directory pages or link lists. Value can be empty or null.
          # str | [str] | null
          - "/search"
          - "/news"
          - "/services"

        REPLACE_CHARACTERS:
          # Characters to be replaced with another one within the scraped content. Values set as "key": "value" -pairs. Can be set as empty or null.
          # "the_string_or_character_to_be_replaced": "the_string_to_replace_with_or_an_empty_string_if_removed"
          "\xa0": " "

        ITEM_PIPELINES:
          # generic.generic.pipelines.NLPPipeline: 300
          # generic.generic.pipelines.SynonymGatheringPipeline: 400
          generic.generic.pipelines.ElasticsearchPipeline: 500

        NLP_SETTINGS:
          # Address for the NLP API if NLPPipeline is used ('http://host.docker.internal:15000' for default) [string | null]
          nlp_api_address: "http://host.docker.internal:15000"
          # File path for the dictionary file ('/usr/share/elasticsearch/data/nlp_dictionary_fi.txt' for default) [string | null]
          nlp_dictionary_path: "/usr/share/elasticsearch/config/nlp_dictionary_fi.txt"
        
        SYNONYM_SETTINGS:
          # Settings for the SynonymGatheringPipeline.
          filepath: "./elasticsearch/synonyms_fi.txt"
          bidirectional: true # Does the synonyms function both ways. word <=> synonyms (true) | word => synonyms (false)
        
        SCRAPER_SETTINGS:
          lang:
            # Where the language is parsed? Default is html element's lang -tag. Can be set as null.
            # Path value points the language value position on the url path. First position is 0 (http://www.site.fi/0/1/2/3/etc)
            "html"
              
          head:
            content_to_scrape:
              og:title:
                element: "meta"
                attribute: "og:title"
                attribute-key: "property"
                attribute-value: "content"
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 5
                  highlight: true
              og:description:
                element: "meta"
                attribute: "og:description"
                attribute-key: "property"
                attribute-value: "content"
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  null
              og:type:
                element: "meta"
                attribute-key: "property"
                attribute: "og:type"
                attribute-value: "content"
                indexing:
                  type: "text"

          body:
            element: "div"
            class: "page-content"
            id: null

            # Define object with ruleset objects to be excluded.
            # All the values are optional and can be set as null.
            exclude_rules:
              # example_ruleset_name:
              #   element: div
              #   class: l-content
              #   id: null
              ruleset1:
                element: "aside"
                class: "l-region"
                id: null

            content_to_scrape:
              header1:
                element: "h1"
                attributes:
                  id: null
                  class: null
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 5
                  highlight: true

              header2:
                element: "h2"
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 3
                  highlight: true

              header3:
                element: "h3"
                attributes":
                  id: null
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  boost: 2
                  highlight: true

              text:
                element: "p"
                attributes:
                  class: null
                indexing:
                  type: "text"
                  analyzer:
                    fi: "stop_stemmer"
                    sv: "stop_stemmer"
                    en: "stop_stemmer"
                search:
                  highlight:
                    no_match_size: 100

#              content_keywords:
#                element: "div"
#                attributes:
#                  class: "field--name-field-keywords"
#                indexing:
#                  type: "text"

              breadcrumb:
                element: "ol"
                attributes: 
                  class: "breadcrumb"

#              content_image:
#                element: "div"
#                attributes:
#                  class: "field__items"
#                image:
#                  target_element: "img"
#                  target_attributes:
#                    class: null
#                    id: null
#                  content_attribute: "src"
#                  alt_text: "alt"
#                  title: "title"
          
        CONTENT_TYPES_AND_THEMES: # Keys directly under this section will be available in UI (not settings)
          settings: 
            parse_content_type_from: "url" # url / element (breadcrumb or other element inside body where it is!)
            parse_themes_from: "breadcrumb" # url / breadcrumb (breadcrumb or element where it is!) / null (if available in e.g. meta tag)
            default_content_type: "tietosivu" # if no match below, use this type
            remove_last_part_from_url_path: true # if true, remove the last section from path which is usually the page itself when parsing theme from url or breadcrumb
            remove_first_part_from_breadcrumb: true # if true, remove the first section from breadcrumb (e.g. "Etusivu") when parsing theme from url or breadcrumb
            remove_last_part_from_breadcrumb: true # if true, remove the last section from breadcrumb which is usually the page itself when parsing theme from url or breadcrumb
            display_fields:
              title: 
                default: ""
                append_values: true
                index_fields:
                  - "og:title"
              text:
                append_values: false
                index_fields:
                  - "og:description"
              publish_date:
                append_values: true
                index_fields:
              modify_date:
                append_values: true
                index_fields:
              writer:
                default:
                suggest: false
                index_fields:
              location:
                index_fields:
                suggest: true
              date: 
                index_fields:
              time:
                index_fields:
              url:
                index_fields:
                  - "url"
              image_url:
                index_fields:
              keywords:
                suggest: false
                index_fields:
                  - "keywords"
              content_type:
                index_fields:
                  - "content_type"
              themes:                 
                suggest: true
                index_fields:
                  - "themes"
          tietosivu:
          uutinen: # The words below get this content type
            - "uutinen"
            - "uutiset"
          blogi:
            - "blogi"
            - "blogit"
          yhteystieto:
            - "yhteystieto"
            - "yhteystiedot"
            - "henkilo"
            - "toimipaikka"
            - "toimipiste"
          tapahtuma:
            - "tapahtuma"
            - "tapahtumat"
          palvelu_tai_asiointikanava:
            - "palvelu"
            - "palvelut"
            - "asiointikanava"
            - "service"
